services:
  # the actual db
  lobby-mongo:
    image: mongo
    container_name: lobby-mongodb-container
    restart: always
    volumes:
      - ./import:/docker-entrypoint-initdb.d:ro
    networks:
      - lobby-internal-net

  # the management interface to the db 
  lobby-mongo-express:
    depends_on:
      - lobby-mongo
    image: mongo-express
    restart: always
    ports:
      # for development purposes only
      - ${LOBBY_DB_UI_PORT:-8081}:8081
    networks:
      - lobby-internal-net 
    environment:
      ME_CONFIG_MONGODB_SERVER: lobby-mongodb-container
      # TODO: use auth to access this or remove entirely on deploy
      ME_CONFIG_BASICAUTH: false

  # the api built on top of the db
  lobby-frontend:
    build: .
    container_name: lobby-api
    depends_on:
      - lobby-mongo
    ports:
      - ${LOBBY_API_PORT}:3000
    networks:
      - lobby-internal-net
      - town-of-saviom-shared-net
    environment:
      # mongodb-container -> nome container del db
      # lobby -> nome del db
      - MONGO_URI=mongodb://lobby-mongodb-container:27017/lobby
      # production or debug
      - NODE_ENV=debug
      # auth-service container url
      - AUTH_SERVICE_URL=#{AUTH_SERVICE_URL}
      # origin url accepted by cors
      - CORS_ORIGIN=http://localhost:5173

networks:
  lobby-internal-net:
    driver: bridge
  town-of-saviom-shared-net:
    external: true