services:
  # the actual db
  lobby-mongo:
    image: mongo
    restart: always
    volumes:
      - ./import:/docker-entrypoint-initdb.d:ro
    networks:
      - lobby-internal-net

  # the management interface to the db 
  lobby-mongo-express:
    depends_on:
      - lobby-mongo
    image: mongo-express
    restart: always
    ports:
      # for development purposes only
      - ${LOBBY_DB_UI_PORT:-8082}:8081
    networks:
      - lobby-internal-net 
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://lobby-mongo:27017/
      - ME_CONFIG_MONGODB_SERVER=lobby-mongo
      # TODO: use auth to access this or remove entirely on deploy
      - ME_CONFIG_BASICAUTH=false

  # the api built on top of the db
  lobby-api:
    build: .
    depends_on:
      - lobby-mongo
    ports:
      - ${LOBBY_API_PORT}:3000
    networks:
      - lobby-internal-net
      - town-of-saviom-shared-net
    environment:
      # mongodb-container -> nome container del db
      # lobby -> nome del db
      - MONGO_URI=mongodb://lobby-mongo:27017/lobby
      # production or debug
      - NODE_ENV=${NODE_ENV}
      # auth-service container url
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      # origin url accepted by cors
      - CORS_ORIGIN=${CORS_ORIGIN}
      # game-service conatiner url (needed to start games)
      - GAME_SERVICE_URL=${GAME_SERVICE_URL}
      # info for internal network use
      # my credentials to send data to gameplay service and gameplay service to delete rooms
      - LOBBY_X_INTERNAL_SERVICE_ID=${LOBBY_X_INTERNAL_SERVICE_ID}
      - GAMEPLAY_X_INTERNAL_SERVICE_ID=${GAMEPLAY_X_INTERNAL_SERVICE_ID}
      - X_INTERNAL_SECRET=${X_INTERNAL_SECRET}

networks:
  lobby-internal-net:
    driver: bridge
  town-of-saviom-shared-net:
    external: true