# Overview of the API
openapi: 3.1.1
info:
  title: Lobby API
  version: 1.0.0
  description: API for managing rooms and lobby information.
          
paths:
  /rooms:
    get:
      summary: Returns a list of rooms.
      tags:
        - Room Info
      security:
        - bearerAuth: []
      produces:
        - application/json
      responses:
        200:
          description: A list of rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
        401:
          description: Unauthorized (Invalid Token or not admin).
    post:
      summary: Adds a new room.
      tags:
        - Room Info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomRequest'
      responses:
        201:
          description: Room added correctly
        400:
          description: Invalid data
        409:
          description: Room already present
  /rooms/room/addPlayer:
    put:
      summary: Update numberOfPlayers
      tags:
        - Room Info
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - numberOfPlayers
                - roomCapacity
              properties:
                numbOfPlayers:
                  type: int
                  example: 6
      responses:
        200:
          description: Number of Players updated correctly.
        401:
          description: Unauthorized (Invalid Token).
        409:
          description: Room already full.
  /rooms/room/removePlayer:
    put:
      summary: Update numberOfPlayers
      tags:
        - Room Info
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - numberOfPlayers
                - roomCapacity
              properties:
                numbOfPlayers:
                  type: int
                  example: 6
      responses:
        200:
          description: Number of Players updated correctly.
        400:
          description: Room already empty.
        401:
          description: Unauthorized (Invalid Token).
  /rooms/room/delete:
    delete:
      summary: Delete room
      tags:
        - Room Info
      security:
        - bearerAuth: []
      responses:
        200:
          description: Room deleted correctly.
        401:
          description: Unauthorized (Invalid Token).

components:
  # -------------------------
  # SECURITY SCHEMES
  # -------------------------
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  # -------------------------
  # DATA SCHEMAS
  # -------------------------
  schemas:

    Room:
      type: object
      properties:
        id:
          type: integer
          example: 123
        code:
          type: string
          example: 123ab
        name:
          type: string
          example: room 1
        gameMode:
          type: string
          example: classic
        numberOfPlayers:
          type: integer
          example: 1
        roomCapacity:
          type: integer
          example: 8

    RoomRequest:
      type: object
      properties:
        code:
          type: string
          example: ciao1
        name:
          type: string
          example: new room
        gameMode:
          type: string
          example: classic
        roomCapacity:
          type: string
          example: 6